-- INSERT REALISTIC TEST SHELTER DATA FOR LOS ANGELES
-- Run this file in Supabase SQL Editor to add test shelters
-- These are FAKE shelters with realistic data for testing only

-- First, we need a provider account.
-- Create a user account in the app with email: provider@test.com
-- Then run this to get the UUID and update it below:
-- SELECT id FROM auth.users WHERE email = 'provider@test.com';

-- IMPORTANT: Replace 'YOUR_PROVIDER_ID_HERE' with the actual UUID from the query above
-- Example: '123e4567-e89b-12d3-a456-426614174000'

DO $$
DECLARE
  provider_uuid UUID := 'YOUR_PROVIDER_ID_HERE'; -- REPLACE THIS!
BEGIN

-- 1. Downtown Emergency Shelter
INSERT INTO listings (
  provider_id,
  title,
  description,
  address,
  city,
  state,
  zip_code,
  lat,
  lng,
  housing_type,
  unit_beds,
  ada_beds,
  gender_rooming,
  amenities,
  accessibility,
  eligibility,
  services,
  rules,
  cost,
  intake,
  availability,
  verified,
  images,
  is_active
) VALUES (
  provider_uuid,
  'Downtown Emergency Shelter',
  'Safe emergency shelter in downtown LA providing immediate housing with on-site case management, meals, and job placement assistance.',
  '123 Main St',
  'Los Angeles',
  'CA',
  '90012',
  34.0522,
  -118.2437,
  'emergency',
  '{"single": 40, "double": 10}'::jsonb,
  5,
  'all',
  '{"showers": true, "laundry": true, "meals": true, "wifi": true, "storage": true}'::jsonb,
  '{"wheelchair": true, "elevator": true, "ada_bathroom": true}'::jsonb,
  '{"age_min": 18, "income_max": null, "background_check": false}'::jsonb,
  '{"case_management": true, "job_placement": true, "mental_health": false, "medical": false}'::jsonb,
  '{"curfew": "10:00 PM", "no_drugs": true, "no_alcohol": true}'::jsonb,
  '{"is_free": true, "nightly_rate": 0}'::jsonb,
  '{"walk_in": true, "appointment": false, "referral_required": false, "hours": "24/7"}'::jsonb,
  '{"beds_today": 15, "beds_week": 20, "waitlist": 5, "last_updated_at": "2024-01-15T10:00:00Z"}'::jsonb,
  true,
  ARRAY['https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800'],
  true
);

-- 2. Women & Children Safe Haven
INSERT INTO listings (
  provider_id,
  title,
  description,
  address,
  city,
  state,
  zip_code,
  lat,
  lng,
  housing_type,
  unit_beds,
  ada_beds,
  gender_rooming,
  amenities,
  accessibility,
  eligibility,
  services,
  rules,
  cost,
  intake,
  availability,
  verified,
  images,
  dv_sensitive,
  is_active
) VALUES (
  provider_uuid,
  'Women & Children Safe Haven',
  'Confidential shelter for women and children fleeing domestic violence. 24/7 crisis support, childcare, legal advocacy, and trauma counseling.',
  '456 Oak Ave',
  'Los Angeles',
  'CA',
  '90015',
  34.0407,
  -118.2468,
  'transitional',
  '{"family": 12, "single": 8}'::jsonb,
  3,
  'women_only',
  '{"childcare": true, "playground": true, "meals": true, "laundry": true, "private_rooms": true}'::jsonb,
  '{"wheelchair": true, "stroller_access": true}'::jsonb,
  '{"age_min": 18, "gender": "female", "children_allowed": true}'::jsonb,
  '{"legal_advocacy": true, "trauma_counseling": true, "childcare": true, "case_management": true}'::jsonb,
  '{"confidential": true, "no_visitors": true, "background_check_guests": true}'::jsonb,
  '{"is_free": true, "nightly_rate": 0}'::jsonb,
  '{"walk_in": false, "appointment": true, "referral_required": true, "hotline": "1-800-799-7233"}'::jsonb,
  '{"beds_today": 4, "beds_week": 6, "waitlist": 12, "last_updated_at": "2024-01-15T08:30:00Z"}'::jsonb,
  true,
  ARRAY['https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800'],
  true,
  true
);

-- 3. Veterans Transitional Housing
INSERT INTO listings (
  provider_id,
  title,
  description,
  address,
  city,
  state,
  zip_code,
  lat,
  lng,
  housing_type,
  unit_beds,
  ada_beds,
  gender_rooming,
  amenities,
  accessibility,
  eligibility,
  services,
  rules,
  cost,
  intake,
  availability,
  verified,
  images,
  is_active
) VALUES (
  provider_uuid,
  'Veterans Transitional Housing',
  'Supportive housing for veterans with VA benefits assistance, job training, and substance abuse programs. Up to 2 year stay while transitioning.',
  '789 Veterans Blvd',
  'Los Angeles',
  'CA',
  '90028',
  34.0928,
  -118.3287,
  'transitional',
  '{"single": 30, "double": 5}'::jsonb,
  8,
  'all',
  '{"gym": true, "computer_lab": true, "meals": true, "laundry": true, "parking": true}'::jsonb,
  '{"wheelchair": true, "elevator": true, "ada_bathroom": true, "hearing_loop": true}'::jsonb,
  '{"veteran": true, "age_min": 18, "honorable_discharge": true}'::jsonb,
  '{"va_benefits": true, "job_training": true, "substance_abuse": true, "ptsd_support": true}'::jsonb,
  '{"sobriety_required": true, "curfew": "11:00 PM", "participate_programs": true}'::jsonb,
  '{"is_free": false, "nightly_rate": 0, "income_percentage": 30}'::jsonb,
  '{"walk_in": false, "appointment": true, "referral_required": true, "va_referral": true}'::jsonb,
  '{"beds_today": 8, "beds_week": 10, "waitlist": 15, "last_updated_at": "2024-01-15T09:00:00Z"}'::jsonb,
  true,
  ARRAY['https://images.unsplash.com/photo-1560184897-502c7a919c76?w=800'],
  true
);

-- 4. Youth Safe Space (18-24)
INSERT INTO listings (
  provider_id,
  title,
  description,
  address,
  city,
  state,
  zip_code,
  lat,
  lng,
  housing_type,
  unit_beds,
  ada_beds,
  gender_rooming,
  amenities,
  accessibility,
  eligibility,
  services,
  rules,
  cost,
  intake,
  availability,
  verified,
  images,
  is_active
) VALUES (
  provider_uuid,
  'Youth Safe Space (18-24)',
  'LGBTQ+ friendly shelter for young adults. Education support, life skills training, mental health services. Pet-friendly.',
  '321 Rainbow St',
  'Los Angeles',
  'CA',
  '90038',
  34.0836,
  -118.3465,
  'emergency',
  '{"single": 25, "shared": 5}'::jsonb,
  2,
  'all',
  '{"pets_allowed": true, "wifi": true, "tutoring": true, "meals": true, "laundry": true}'::jsonb,
  '{"wheelchair": true, "gender_neutral_bathroom": true}'::jsonb,
  '{"age_min": 18, "age_max": 24, "lgbtq_friendly": true}'::jsonb,
  '{"ged_prep": true, "college_prep": true, "life_skills": true, "mental_health": true}'::jsonb,
  '{"respect_all": true, "no_discrimination": true, "curfew": "midnight"}'::jsonb,
  '{"is_free": true, "nightly_rate": 0}'::jsonb,
  '{"walk_in": true, "appointment": false, "hours": "24/7", "youth_line": "1-800-786-2929"}'::jsonb,
  '{"beds_today": 12, "beds_week": 15, "waitlist": 3, "last_updated_at": "2024-01-15T11:30:00Z"}'::jsonb,
  true,
  ARRAY['https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800'],
  true
);

-- 5. Family Housing Program
INSERT INTO listings (
  provider_id,
  title,
  description,
  address,
  city,
  state,
  zip_code,
  lat,
  lng,
  housing_type,
  unit_beds,
  ada_beds,
  gender_rooming,
  amenities,
  accessibility,
  eligibility,
  services,
  rules,
  cost,
  intake,
  availability,
  verified,
  images,
  is_active
) VALUES (
  provider_uuid,
  'Family Housing Program',
  'Private family units with kitchen facilities. Childcare, school enrollment assistance, parenting classes. Up to 90 day stay.',
  '555 Family Ln',
  'Los Angeles',
  'CA',
  '90019',
  34.0522,
  -118.3089,
  'transitional',
  '{"family_2br": 10, "family_3br": 5}'::jsonb,
  4,
  'families',
  '{"kitchen": true, "childcare": true, "playground": true, "laundry": true, "parking": true}'::jsonb,
  '{"wheelchair": true, "stroller_access": true, "elevator": true}'::jsonb,
  '{"children_required": true, "family_unit": true}'::jsonb,
  '{"childcare": true, "school_enrollment": true, "parenting_classes": true, "job_placement": true}'::jsonb,
  '{"school_attendance": true, "participate_programs": true}'::jsonb,
  '{"is_free": true, "nightly_rate": 0, "max_days": 90}'::jsonb,
  '{"walk_in": false, "appointment": true, "referral_required": true}'::jsonb,
  '{"beds_today": 6, "beds_week": 8, "waitlist": 20, "last_updated_at": "2024-01-15T07:45:00Z"}'::jsonb,
  true,
  ARRAY['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
  true
);

-- 6. Sober Living Community
INSERT INTO listings (
  provider_id,
  title,
  description,
  address,
  city,
  state,
  zip_code,
  lat,
  lng,
  housing_type,
  unit_beds,
  ada_beds,
  gender_rooming,
  amenities,
  accessibility,
  eligibility,
  services,
  rules,
  cost,
  intake,
  availability,
  verified,
  images,
  is_active
) VALUES (
  provider_uuid,
  'Sober Living Community',
  'Substance-free supportive housing with 12-step meetings, peer support, and recovery coaching. Work requirement after 30 days.',
  '888 Recovery Rd',
  'Los Angeles',
  'CA',
  '90026',
  34.0736,
  -118.2615,
  'permanent_supportive',
  '{"single": 20, "double": 10}'::jsonb,
  3,
  'all',
  '{"meeting_room": true, "gym": true, "meals": true, "laundry": true}'::jsonb,
  '{"wheelchair": true, "ada_bathroom": true}'::jsonb,
  '{"sobriety_required": true, "age_min": 18, "commitment_6months": true}'::jsonb,
  '{"12_step_meetings": true, "peer_support": true, "recovery_coaching": true, "job_placement": true}'::jsonb,
  '{"drug_testing": true, "attend_meetings": true, "work_requirement": true, "curfew": "10:00 PM"}'::jsonb,
  '{"is_free": false, "monthly_rate": 500, "work_exchange_available": true}'::jsonb,
  '{"walk_in": false, "appointment": true, "referral_required": false, "interview_required": true}'::jsonb,
  '{"beds_today": 5, "beds_week": 8, "waitlist": 10, "last_updated_at": "2024-01-15T10:15:00Z"}'::jsonb,
  true,
  ARRAY['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800'],
  true
);

-- 7. Senior Safe Housing
INSERT INTO listings (
  provider_id,
  title,
  description,
  address,
  city,
  state,
  zip_code,
  lat,
  lng,
  housing_type,
  unit_beds,
  ada_beds,
  gender_rooming,
  amenities,
  accessibility,
  eligibility,
  services,
  rules,
  cost,
  intake,
  availability,
  verified,
  images,
  is_active
) VALUES (
  provider_uuid,
  'Senior Safe Housing',
  'Supportive housing for seniors 62+. Medical support, mobility assistance, social activities. Ground floor accessible units.',
  '999 Elder Way',
  'Los Angeles',
  'CA',
  '90045',
  33.9584,
  -118.3897,
  'permanent_supportive',
  '{"single": 15, "ada": 10}'::jsonb,
  10,
  'all',
  '{"medical_support": true, "meals": true, "activities": true, "elevator": true, "grab_bars": true}'::jsonb,
  '{"wheelchair": true, "walker_friendly": true, "emergency_call": true, "ground_floor": true}'::jsonb,
  '{"age_min": 62, "mobility_issues_ok": true}'::jsonb,
  '{"nursing_visits": true, "meal_delivery": true, "social_activities": true, "medicare_assistance": true}'::jsonb,
  '{"no_smoking": true, "quiet_hours": "9:00 PM"}'::jsonb,
  '{"is_free": true, "nightly_rate": 0}'::jsonb,
  '{"walk_in": false, "appointment": true, "referral_required": true}'::jsonb,
  '{"beds_today": 3, "beds_week": 5, "waitlist": 25, "last_updated_at": "2024-01-15T06:00:00Z"}'::jsonb,
  true,
  ARRAY['https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=800'],
  true
);

END $$;

-- After running this:
-- 1. Verify data loaded: SELECT COUNT(*) FROM listings;
-- 2. Check one listing: SELECT title, availability FROM listings LIMIT 1;
-- 3. Test in app: Open search screen and see if shelters appear
